### ISSUE TITLE
MySQL-python - don't follow README instructions, just untar and copy files to lambda folder

### ISSUE THREAD

**Issue by ryantuck** [Miserlou/lambda-packages#5]
following the readme instructions for `MySQL-python` doesn't work on amazon linux. 

instead, untarring the contents of the tar file and copying them does the trick.

by the way, thank you SO MUCH for this repo - was banging my head against the wall for hours trying to get this to work! :+1:

**Comment by Miserlou** [comment]
Sure thing!

The instructions in the README are there so that we can re-make the build deterministicly for new versions of the packages, not for average users, who should just be able to use the archives. Ideally, we'll do this automatically with Vagrant or something similar.

Thanks for reporting though, glad you're making good use of the project.
